name: Lint

on: pull_request

jobs:
  Prettier:
    name: Prettier
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node_version: "lst/hydrogen"

      - run: npm ci

      - run: npm run lint:prettier:check
